sass:
    sass_dir: _scss
keep_files: [ 'resume.pdf', 'keybase.txt', 'complication.txt' ]
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-compress-images
title: Stay Caffeinated
description: Coffee, Software, AI, and a few Aliens
author: Mike Lyons
url: https://staycaffeinated.com
compress_images:
  images_path: "images/guitar/*.{gif,png,jpg,jpeg,svg}"
