sass:
    sass_dir: _scss
keep_files: [ 'resume.pdf', 'keybase.txt', 'complication.txt' ]
plugins:
- jekyll-sitemap
- jekyll-feed
title: Stay Caffeinated
description: Coffee, Software, AI, and a few Aliens
author: Mike Lyons
url: https://staycaffeinated.com